#!/usr/bin/python3

numbers = [1, 2, 3]
# Python will throw an out of bounds exception here:
print("The fourth number is:", numbers[3])
